config/routes.rb
require 'sidekiq/web'

ForeverFamilyFoundation::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'site#index'

  match '/404', to: 'exceptions#not_found', via: :all
  match '/500', to: 'exceptions#internal_error', via: :all
  match '/422', to: 'exceptions#unacceptable', via: :all

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :user do
    root 'users#show' # creates user_root_path
  end

  resources :users, only: :show
  resources :businesses
  resources :subscriptions

  # begin old routes
  resources :belief_types
  resources :tests
  resources :known_deads
  resources :relationships

  resources :events
  resources :radio_archives
  resources :recommended_book
  resource :adg_registration
  resource :redirects
  resources :sitterforms
  resources :mediumforms
  resources :known_deads

  get '/businesses/welcome/:id' => 'businesses#welcome', as: 'businesses_welcome'
  get '/users/welcome/:id' => 'users#welcome', as: 'users_welcome'

  # Redirects
  get '/sitemap' => 'redirects#sitemap' #'http://s3.amazonaws.com/fff_attached_files/attached_files/attachments/000/000/670/original/sitemap.xml?2016'
  get '/certifiedmediums' => 'redirects#certified_mediums'
  get '/Suicide' => 'redirects#suicide'
  get '/contributions' => 'redirects#contributions'
  get '/signsofliferadio' => 'redirects#signs_of_life_radio'
  get '/signsofliferadioLISTEN' => 'redirects#signs_of_life_radio'
  get '/radio' => 'redirects#signs_of_life_radio'
  get '/radio2007' => 'redirects#signs_of_life_radio'
  get '/SanFransiscoTravel' => 'redirects#home_page'
  get '/NewYork2008CC' => 'redirects#home_page'
  get '/images/Events/TG0726-2813CT-SponsorProgramOpp.pdf' => 'redirects#home_page'
  get '/images/Events/TG0520-2211CT-FLYER2v4TABS.pdf' => 'redirects#home_page'
  get '/mobile/events/94' => 'redirects#events'
  get '/FMC2010' => 'redirects#events'
  get '/images/SF2008IMAGES/SF2008ProgramPRG.pdf' => 'redirects#events'
  get '/bookreview' => 'redirects#recommended_books'
  get '/images/GuestHouse/TheGuestHouse-brochure' => 'redirects#guest_house_brochure'
  get '/site/:action' => 'site#page', as: 'page'
  get '/site/page/:id' => 'site#page', as: 'page_by_id'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :continue_registration, only: [:new]

  def new
    params[:step] ||= 1
    @business = current_user.business || Business.new
  end

  def create
    @business = current_user.build_business(params[:business])
    if @business.save
      @business.complete_step!(1)
      flash[:notice] = I18n.t('flash.business.create.success', step: 1)
      redirect_to user_business_payment_path(current_user, @business)
    else
      render :new
    end
  end

  def payment
    @user = current_user
    @business = @user.business
    if request.post?
      begin
        Stripe::Charge.create(
          amount: (ConfigVariable.find_by_name('Price').try(:value) || 100).to_i * 100,
          currency: "usd",
          card: {
            number: params[:credit_card][:number],
            exp_month: params[:credit_card][:exp_month],
            exp_year: params[:credit_card][:exp_year],
            cvc: params[:credit_card][:cvc],
            name: params[:credit_card][:name]
          },
          description: "Forever Family Foundation business membership"
        )
        flash[:notice] = I18n.t('flash.business.payment.success')
        redirect_to user_business_register_path(current_user, @business, step: 3)
      rescue Stripe::CardError, Stripe::InvalidRequestError  => e

        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        @business.errors.add(:base, body[:error][:message])
        render :payment
        # puts "Status is: #{e.http_status}"
        # puts "Type is: #{err['type']}"
        # puts "Code is: #{err['code']}"
        # param is '' in this case
        # puts "Param is: #{err['param']}"
        # puts "Message is: #{err['message']}"
      # rescue Stripe::AuthenticationError => e
      #   # Authentication with Stripe's API failed
      #   # (maybe you changed API keys recently)
      # rescue Stripe::APIConnectionError => e
      #   # Network communication with Stripe failed
      # rescue Stripe::StripeError => e
        # Display a very generic error to the user, and maybe send
        # yourself an email
      end
    else
      render :payment
    end
  end

  def register
    next_step = params[:step].to_i + 1  #   session[:step] + 1

    @user = current_user
    @business = current_user.business

    if request.put? && @business.update_attributes(params[:business])
      @business.complete_step!(params[:step])
      flash[:notice] = I18n.t('flash.business.create.success', step: params[:step])

      redirect_to user_path(@user) and return if @business.reg_complete?

      redirect_to user_business_register_path(
        current_user, current_user.business,
      step: next_step )
    else
      render :register
    end
  end

  def edit
    @business = current_user.business
  end

  def update
    @business = current_user.business
    if @business.update_attributes(params[:business])
      flash[:notice] = I18n.t('flash.business.update.success')
      redirect_to user_path(current_user)
    else
      render template: "businesses/edit"
    end

  end

  def attachment
    attached_file = current_user.business.attached_files.find(params[:attachment_id])
    send_file attached_file.attachment.path, :type => attached_file.attachment.content_type
  end

  private

  def continue_registration
    if !params[:step].nil?
      if params[:step]==2
        render :payment
      else
        redirect_to user_business_register_path(
          current_user, current_user.business,
        step: params[:step])
      end
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def step_link(step, completed, current_step)
    case completed
    when true
      if step.to_i == current_step.to_i
        content_tag :span, "Step #{step}"
      else
        link(step)
      end
      
    when false
      if step.to_i == current_step.to_i
        content_tag :span, "Step #{step}"
      else
        if step.to_i >= current_step.to_i
          "Step #{step}"
        else
          link(step)
        end
      end
    end
  end  
  
  def link(step)
    link_to "Step #{step}", edit_user_business_path(current_user, @business, step: step)
  end
end

app/views/businesses/_form.html.haml
.form_section
  %h2 Business information
  .form_fields
    .group.biz_address
      = form.input :name, label: t('name_of_business')          	
      = form.fields_for :address do |address_form|
        = address_form.input :address, label: t('labels.address'), required: true, input_html: { class: :address }
        = address_form.input :city, label: t('labels.city'), required: true, input_html: { class: :city }
        = address_form.input :state, label: t('labels.state'), required: true, input_html: { class: :state }
        = address_form.input :zip, label: t('labels.zip'), required: true, input_html: { class: :zip }
      = form.input :contact_name, label: t('labels.contact_name'), required: true                    
      = form.input :contact_phone, label: t('labels.contact_phone'), required: true
      = form.input :contact_email, label: t('labels.contact_email'), required: true
      = form.input :contact_email_confirmation, label: t('labels.contact_email_confirmation'), required: true
      = form.input :fax, label: t('labels.fax_number')

.form_section
  %h2 Billing Address
  .form_fields
    %p.use_biz_address
      = check_box_tag :use_biz_address
      %label{ for: :use_biz_address} Use Business Address
    .group.billing_address
      = form.fields_for :billing_address do |billing_address_form|
        = billing_address_form.input :address, label: t('labels.address'), required: true, input_html: { class: :address }
        = billing_address_form.input :city, label: t('labels.city'), required: true, input_html: { class: :city }
        = billing_address_form.input :state, label: t('labels.state'), required: true, input_html: { class: :state }
        = billing_address_form.input :zip, label: t('labels.zip'), required: true, input_html: { class: :zip }
        = billing_address_form.country_select :country, [["United States", 'US']]        

app/views/businesses/_form_1.html.haml
= render "shared/error_messages", :target => @business
= hidden_field_tag :step, 1
.form_section
  %h2.form_section_header Business information
  .form_fields
    .group.biz_address
      = f.input :name, label: t('name_of_business')
      = f.fields_for :address do |address_form|
        = address_form.input :address, label: t('labels.address'), required: true, input_html: { class: :address }
        = address_form.input :city, label: t('labels.city'), required: true, input_html: { class: :city }
        = address_form.input :state, label: t('labels.state'), required: true, input_html: { class: :state }
        = address_form.input :zip, label: t('labels.zip'), required: true, input_html: { class: :zip }
        = address_form.input :country, priority: ["United States"], input_html: { class: :country }
        %br
      = f.input :contact_name, label: t('labels.contact_name'), required: true
      = f.input :contact_phone, label: t('labels.contact_phone'), required: true
      = f.input :contact_email, label: t('labels.contact_email'), required: true
      = f.input :contact_email_confirmation, label: t('labels.contact_email_confirmation'), required: true
      = f.input :fax, label: t('labels.fax_number')

.form_section
  %h2.form_section_header Billing Address
  .form_fields
    %p.use_biz_address
      = check_box_tag :use_biz_address
      %label{ for: :use_biz_address} Use Business Address
    .group.billing_address
      = f.fields_for :billing_address do |billing_address_form|
        = billing_address_form.input :address, label: t('labels.address'), required: true, input_html: { class: :address }
        = billing_address_form.input :city, label: t('labels.city'), required: true, input_html: { class: :city }
        = billing_address_form.input :state, label: t('labels.state'), required: true, input_html: { class: :state }
        = billing_address_form.input :zip, label: t('labels.zip'), required: true, input_html: { class: :zip }
        = billing_address_form.input :country, priority: ["United States"], input_html: { class: :country }

app/views/businesses/_form_3.html.haml
= hidden_field_tag :step, 3

.form_section
  %h2.form_section_header Business Media
  .form_fields

    = f.fields_for :business_card do |business_card_form|
      %fieldset
        %legend= business_card_form.label :attachment, t('labels.business_card')
        - if @business.business_card.attachment.present?
          .thumbnail= image_tag  @business.business_card.attachment.url(:thumb)
        = business_card_form.file_field :attachment
        = business_card_form.hidden_field :kind

    = f.fields_for :business_logo do |business_logo_form|
      %fieldset
        %legend= business_logo_form.label :attachment, t('labels.business_logo')
        - if @business.business_logo.attachment.present?
          .thumbnail= image_tag  @business.business_logo.attachment.url(:thumb)
        = business_logo_form.file_field :attachment
        = business_logo_form.hidden_field :kind


    = f.fields_for :web_banner do |web_banner_form|
      %fieldset
        %legend= web_banner_form.label :attachment, t('labels.web_banner')
        - if @business.web_banner.attachment.present?
          .thumbnail= image_tag  @business.web_banner.attachment.url(:thumb)
        = web_banner_form.file_field :attachment
        = web_banner_form.hidden_field :kind

        %br
        %br
        %p
          = f.check_box :use_business_card_for_web_banner
          = f.label :use_business_card_for_web_banner, t('labels.use_business_card_for_web_banner')

    %p
      = f.label :promotional_info_additional_notes, t('labels.additional_notes')
      = f.text_area :promotional_info_additional_notes, :class => 'simple'

app/views/businesses/_form_4.html.haml
= hidden_field_tag :step, 4

.form_section
  %h2.form_section_header Promotional Media
  .form_fields

    = f.fields_for :promotional_media_mp3 do |promotional_media_mp3_form|

      %fieldset
        %legend= promotional_media_mp3_form.label :attachment, t('labels.promotional_media_mp3')
        - if @business.promotional_media_mp3.attachment.present?
          %audio{ controls: "controls", src: @business.promotional_media_mp3.attachment.url, type: "audio/mp3" }
            %p= link_to @business.promotional_media_mp3.attachment.original_filename, @business.promotional_media_mp3.attachment.url
          %p== If the audio player, above, does not work in your browser you can download the audio file #{link_to 'here', @business.promotional_media_mp3.attachment.original_filename}.
        = promotional_media_mp3_form.file_field :attachment
        = promotional_media_mp3_form.hidden_field :kind


      = f.fields_for :promotional_media_upload do |promotional_media_upload_form|
        %fieldset
          %legend= promotional_media_upload_form.label :attachment, t('labels.promotional_media_upload')
          - if @business.promotional_media_upload.attachment.present?
            .thumbnail=  link_to "#{@business.promotional_media_upload.attachment.original_filename} (Dowload)", @business.promotional_media_upload.attachment.url
          = promotional_media_upload_form.file_field :attachment
          = promotional_media_upload_form.hidden_field :kind


      %p
        = f.label :promotional_media_text
        = f.text_area :promotional_media_text

      %p
        = f.label :promotional_media_additional_notes, t('labels.additional_notes')
        = f.text_area :promotional_media_additional_notes, :class => 'simple'

app/views/businesses/_steps.html.haml
%p.step_indicator 
  = step_link(1, @business.completed_step?(1), params[:step] || 1)
  >
  = step_link(2, @business.completed_step?(2), params[:step] || 1)
  >
  = step_link(3, @business.completed_step?(3), params[:step] || 1)
  >
  = step_link(4, @business.completed_step?(4), params[:step] || 1)
  

app/views/businesses/edit.html.haml
= render :partial => 'steps'
= simple_form_for setup_business(@business), :url => user_business_path(current_user, @business) do |f|
  = render partial: "form_#{params[:step]}", locals: { f: f }
  = render partial: 'shared/form_submit', locals: { text: t('buttons.update') }

app/views/businesses/edit_step_5.html.haml
- @user = @business.user
= render 'users/details'
= form_for @user, :url => user_business_path(current_user, @business), :html => { :multipart => true } do |f|
    = hidden_field_tag :step, 5
    = render :partial => 'shared/form_submit', :locals => { :text => t('buttons.confirm') }
    

app/views/businesses/new.html.haml
= render :partial => 'steps'
= simple_form_for setup_business(@business), :url => "/users/#{current_user.id}/businesses" do |f|
  = render partial: "form_#{params[:step]}", locals: { f: f }
  = render partial: 'shared/form_submit_business', locals: { text: t('buttons.submit') }

app/views/businesses/payment.html.haml
= render("shared/error_messages", target: @business) if @business
= simple_form_for :credit_card, :url => user_business_payment_path(@user, @business) do |f|
  .form_section
    %h2.form_section_header Payment Information
    .form_fields
      = hidden_field_tag :step, 2
      = f.input :name, label: I18n.t('labels.credit_card_name')
      = f.input :number, label: I18n.t('labels.credit_card_number')
      = f.input :cvc, input_html: { maxlength: 4 }, label: I18n.t('labels.credit_card_cvc')

      %p.input.select.required
      = f.input :exp_month, as: :select, :collection => 1..12, prompt: 'MM', label: I18n.t('labels.credit_card_exp'), wrapper: false
      = f.input :exp_year, as: :select, :collection => Date.today.year..10.years.from_now.year, prompt: 'YYYY', label: false, wrapper: false

      %p.red
        * Your credit card will be charged the Business Membership Fee of
        = number_to_currency ConfigVariable.find_by_name('Price').try(:value)

  = render partial: 'shared/form_submit', locals: { text: 'Submit Payment' }

app/views/businesses/register.html.haml
- button_text = [3,4].include?(params[:step].to_i) ? t('buttons.submit_or_skip') : t('buttons.submit')
= render :partial => 'steps'
= simple_form_for setup_business(@business), url: user_business_register_path(current_user, @business), method: :put do |f|
  = render partial: "form_#{params[:step]}", locals: { f: f }
  = render partial: 'shared/form_submit', locals: { text: button_text }