config/routes.rb
require 'sidekiq/web'

ForeverFamilyFoundation::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'site#index'

  match '/404', to: 'exceptions#not_found', via: :all
  match '/500', to: 'exceptions#internal_error', via: :all
  match '/422', to: 'exceptions#unacceptable', via: :all

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :user do
    root 'users#show' # creates user_root_path
  end

  resources :users, only: :show
  resources :businesses
  resources :subscriptions

  # begin old routes
  resources :belief_types
  resources :tests
  resources :known_deads
  resources :relationships

  resources :events
  resources :radio_archives
  resources :recommended_book
  resource :adg_registration
  resource :redirects
  resources :sitterforms
  resources :mediumforms
  resources :known_deads

  get '/businesses/welcome/:id' => 'businesses#welcome', as: 'businesses_welcome'
  get '/users/welcome/:id' => 'users#welcome', as: 'users_welcome'

  # Redirects
  get '/sitemap' => 'redirects#sitemap' #'http://s3.amazonaws.com/fff_attached_files/attached_files/attachments/000/000/670/original/sitemap.xml?2016'
  get '/certifiedmediums' => 'redirects#certified_mediums'
  get '/Suicide' => 'redirects#suicide'
  get '/contributions' => 'redirects#contributions'
  get '/signsofliferadio' => 'redirects#signs_of_life_radio'
  get '/signsofliferadioLISTEN' => 'redirects#signs_of_life_radio'
  get '/radio' => 'redirects#signs_of_life_radio'
  get '/radio2007' => 'redirects#signs_of_life_radio'
  get '/SanFransiscoTravel' => 'redirects#home_page'
  get '/NewYork2008CC' => 'redirects#home_page'
  get '/images/Events/TG0726-2813CT-SponsorProgramOpp.pdf' => 'redirects#home_page'
  get '/images/Events/TG0520-2211CT-FLYER2v4TABS.pdf' => 'redirects#home_page'
  get '/mobile/events/94' => 'redirects#events'
  get '/FMC2010' => 'redirects#events'
  get '/images/SF2008IMAGES/SF2008ProgramPRG.pdf' => 'redirects#events'
  get '/bookreview' => 'redirects#recommended_books'
  get '/images/GuestHouse/TheGuestHouse-brochure' => 'redirects#guest_house_brochure'
  get '/site/:action' => 'site#page', as: 'page'
  get '/site/page/:id' => 'site#page', as: 'page_by_id'
end

app/controllers/adg_registrations_controller.rb
class AdgRegistrationsController < ApplicationController
  before_action :require_registration, :only => [:new]

  def new
    session[:adg_registration] = nil
    @adg_questions = AdgQuestion.all
  end

  def create
    adg_answers = params[:adg_registration][:answer]
    adg_radio_val_hash = params[:adg_registration][:radio_val] || {}
    adg_answers.each_pair do |question_id, answer|
      adg_question = AdgQuestion.find(question_id)
      adg_answer = current_user.adg_answers.find_or_create_by(adg_question_id: adg_question.id)
      adg_answer.answer = answer
      adg_answer.radio_val = adg_radio_val_hash[question_id]
      adg_answer.question = adg_question.question
      adg_answer.save!
    end
    current_user.update_attribute(:adg_preference_ids, params[:adg_registration][:adg_preference_ids])
    UserNotifier.send_adg_email(current_user)

    flash[:notice] = I18n.t('flash.adg.answers_updated')
    redirect_to current_user
  end

  private

  def require_registration
    if current_user.blank?
      session[:adg_registration] = true
      flash[:notice] = I18n.t('flash.adg.user_required')
      redirect_to new_user_registration_path
    end
  end
end

app/views/admin/adg_registrations/edit.html.haml
- form_tag admin_user_adg_registration_path(@user), :method => :put do
  %table
    - @adg_questions.each do |adg_question|
      %tr
        %td= adg_question.question
        %td
          - @adg_answers.blank? ? adg_answer = '' : adg_answer = @adg_answers.assoc(adg_question.id)[1]          
          - if adg_question.show_radio
            Yes
            = radio_button "adg_registration", "radio_val[#{adg_question.id}]", "yes", :onclick => "show_text_area('#{adg_question.id}')", :checked => (@adg_answers.assoc(adg_question.id)[2] == "yes" unless @adg_answers.assoc(adg_question.id).blank?)
            /
            No
            = radio_button "adg_registration", "radio_val[#{adg_question.id}]", "no", :onclick => "hide_text_area('#{adg_question.id}')", :checked => (@adg_answers.assoc(adg_question.id)[2] == "no" unless @adg_answers.assoc(adg_question.id).blank?)
            - adg_answer.blank? ? display = "hide" : display = ''
            %div= text_area_tag "adg_registration[answer[#{adg_question.id}]]", adg_answer, :class => "simple #{display}" 
          - else
            = text_area_tag "adg_registration[answer[#{adg_question.id}]]", adg_answer, :class => 'simple'

  - user_adg_preferences = @user.adg_preferences.all
  - Preference.adg_preferences.each do |adg_preference|
    = check_box_tag "adg_registration[adg_preference_ids][]", adg_preference.id, user_adg_preferences.include?(adg_preference) 
    = adg_preference.name
    %br
    %br
  = render :partial => 'shared/form_submit', :locals => { :text => t('save') }

:javascript
  function show_text_area(adg_question_id) {
    $('adg_registration_answer_'+adg_question_id).show();
  }

  function hide_text_area(adg_question_id) {
    $('adg_registration_answer_'+adg_question_id).hide();
  }

app/views/admin/adg_registrations/show.html.haml
- @adg_answers.each do |adg_answer|
  %p
    = adg_answer.question
    %br
    = "#{ "#{adg_answer.radio_val.capitalize} -" unless adg_answer.radio_val.blank?} #{adg_answer.answer}"
- user_adg_preferences = @user.adg_preferences.all
- Preference.adg_preferences.each do |adg_preference|
  = adg_preference.name
  = user_adg_preferences.include?(adg_preference) ? " - Yes" : " - No"
  %br
  %br
%br
= link_to "Edit", edit_admin_user_adg_registration_path(@user)