config/routes.rb
require 'sidekiq/web'

ForeverFamilyFoundation::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'site#index'

  match '/404', to: 'exceptions#not_found', via: :all
  match '/500', to: 'exceptions#internal_error', via: :all
  match '/422', to: 'exceptions#unacceptable', via: :all

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :user do
    root 'users#show' # creates user_root_path
  end

  resources :users, only: :show
  resources :businesses
  resources :subscriptions

  # begin old routes
  resources :belief_types
  resources :tests
  resources :known_deads
  resources :relationships

  resources :events
  resources :radio_archives
  resources :recommended_book
  resource :adg_registration
  resource :redirects
  resources :sitterforms
  resources :mediumforms
  resources :known_deads

  get '/businesses/welcome/:id' => 'businesses#welcome', as: 'businesses_welcome'
  get '/users/welcome/:id' => 'users#welcome', as: 'users_welcome'

  # Redirects
  get '/sitemap' => 'redirects#sitemap' #'http://s3.amazonaws.com/fff_attached_files/attached_files/attachments/000/000/670/original/sitemap.xml?2016'
  get '/certifiedmediums' => 'redirects#certified_mediums'
  get '/Suicide' => 'redirects#suicide'
  get '/contributions' => 'redirects#contributions'
  get '/signsofliferadio' => 'redirects#signs_of_life_radio'
  get '/signsofliferadioLISTEN' => 'redirects#signs_of_life_radio'
  get '/radio' => 'redirects#signs_of_life_radio'
  get '/radio2007' => 'redirects#signs_of_life_radio'
  get '/SanFransiscoTravel' => 'redirects#home_page'
  get '/NewYork2008CC' => 'redirects#home_page'
  get '/images/Events/TG0726-2813CT-SponsorProgramOpp.pdf' => 'redirects#home_page'
  get '/images/Events/TG0520-2211CT-FLYER2v4TABS.pdf' => 'redirects#home_page'
  get '/mobile/events/94' => 'redirects#events'
  get '/FMC2010' => 'redirects#events'
  get '/images/SF2008IMAGES/SF2008ProgramPRG.pdf' => 'redirects#events'
  get '/bookreview' => 'redirects#recommended_books'
  get '/images/GuestHouse/TheGuestHouse-brochure' => 'redirects#guest_house_brochure'
  get '/site/:action' => 'site#page', as: 'page'
  get '/site/page/:id' => 'site#page', as: 'page_by_id'
end

app/models/known_dead.rb
class KnownDead < ActiveRecord::Base
  belongs_to :user
  belongs_to :relationship
  belongs_to :sitterform

  attr_accessible :id, :name, :relationship_id, :sitterform_id, :year_of_death
end

app/controllers/known_deads_controller.rb
class KnownDeadsController < ApplicationController
  before_action :set_known_dead, only: [:show, :edit, :update, :destroy]

  def index
    logger.debug "----- Sitterforms index -----"
    @known_dead = KnownDead.all
  end

  def new
    logger.debug "----- KnownDead index -----"
    @known_dead = KnownDead.new
  end

  # POST /sitterforms
  # POST /sitterforms.json
  def create
    logger.debug "----- KnownDead create -----"
    @known_dead = KnownDead.new(known_dead_params)

    respond_to do |format|
      if @known_dead.save
        format.html { redirect_to @known_dead, notice: 'Sitterform was successfully created.' }
        format.json { render :show, status: :created, location: @known_dead }
      else
        format.html { render :new }
        format.json { render json: @known_dead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    logger.debug "KnownDead Update -----"
    respond_to do |format|
      if @known_dead.update(known_dead_params)
        format.html { redirect_to @known_dead, notice: 'KnownDead was successfully updated.' }
        format.json { render :show, status: :ok, location: @known_dead }
      else
        format.html { render :edit }
        format.json { render json: @known_dead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @known_dead.destroy
    respond_to do |format|
      format.html { redirect_to known_deads_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_known_dead
      @known_dead = KnownDead.find(params[:id])
    end

    def known_dead_params
      params.require(:known_dead).permit(:id, :user_id, :relationship_id, :sitterform_id, :name, :relationship, :year_of_death)
    end
end

app/views/known_deads/_known_dead_form.html.erb
<%= simple_form_for(@known_dead) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :user_id %>
    <%= f.input :sitterform_id %>
    <%= f.input :name %>
    <%= f.select :relationship_id, Relationship.all.collect { |p| [ p.name, p.id ] } %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/known_deads/edit.html.erb
<h1>Editing Known Dead</h1>

<%= render 'known_dead_form' %>

<%= link_to 'Show', @known_dead %> |
<%= link_to 'Back', known_deads_path %>

app/views/known_deads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Known Deads</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User ID</th>
      <th>Sitterform ID</th>
      <th>Name</th>
      <th>Relationship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @known_dead.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td><%= f.user_id %></td>
        <td><%= f.sitterform_id %></td>
        <td><%= f.name %></td>
        <td><%= f.relationship.name %></td>
        <td><%= link_to 'Show', f %></td>
        <td><%= link_to 'Edit', edit_known_dead_path(f) %></td>
        <td><%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Known dead', new_known_dead_path %>

app/views/known_deads/new.html.erb
<h1>New Known Dead</h1>

<%= render 'known_dead_form' %>

<%= link_to 'Back', known_deads_path %>

app/views/known_deads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @known_dead.user_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @known_dead.name %>
</p>
<p>


<%= link_to 'Edit', edit_known_dead_path(@known_dead) %> |
<%= link_to 'Back', known_deads_path %>